/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id:
    'us-east-2:2fa1b463-d5d8-4885-97e4-b4cd25264830',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_AcaaJKLqB',
  aws_user_pools_web_client_id: '593gnc3qdo6jfm0itc2tgdt02g',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://3zx3wy7xs5cc5d2efys73dyyva.appsync-api.us-east-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-2',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-vjc3uql2cndi5a7yevuxdsvtku',
  aws_user_files_s3_bucket: 'demo94742-dev',
  aws_user_files_s3_bucket_region: 'us-east-2',
};

export default awsmobile;
